packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"
  - "services/*"

# Dependencies allowed to run install scripts.
allowBuilds:
  '@irsdk-node/native': true
  esbuild: true
  koffi: true
  electron-winstaller: false
